ALTER TABLE spaces DROP COLUMN IF EXISTS visibility;
ALTER TABLE spaces DROP COLUMN IF EXISTS allowed_teams;
ALTER TABLE spaces DROP COLUMN IF EXISTS allowed_users;

ALTER TABLE projects DROP COLUMN IF EXISTS visibility;
ALTER TABLE projects DROP COLUMN IF EXISTS allowed_teams;
ALTER TABLE projects DROP COLUMN IF EXISTS allowed_users;

ALTER TABLE teams DROP COLUMN IF EXISTS avatar;
ALTER TABLE teams DROP COLUMN IF EXISTS color;
